### ISSUE TITLE
transform don't work...

### ISSUE THREAD

**Issue by yfrindel** [nunit/nunit-transforms#4] opened 2016-12-01 18:24 UTC
as you can see, the command don't work...I don't know why...please, help !

![issue](https://cloud.githubusercontent.com/assets/22955005/20806582/cd08e29c-b7fb-11e6-8a2f-a7908a3e56f8.JPG)

**Comment by CharliePoole** [comment] 2016-12-01 19:25
The most likely cause of the message is that the transform is not present in the directory.

**Comment by yfrindel** [comment] 2016-12-01 20:13
thank you for the answer. Which directory are you talking about please ?

**Comment by rprouse** [comment] 2016-12-01 20:27
@yfrindel, which directory do you have `nunit3-junit.xslt` in? I need to look at the code, but my guess that it needs to be in the directory you are running `nunit3-console.exe` from. In your case, the `UnitTests` directory that you show on your command line. If not, you need to supply the path to the XSLT file.

**Comment by rprouse** [comment] 2016-12-01 20:28
This is also the wrong repository for this issue. This repository is for a currently unreleased transform tool. I am going to mark this issue as a question and close it because I think you just need help getting your paths right. Feel free to ask more questions here, we will see them even if the issue is closed.

**Closed by rprouse** 2016-12-01 20:28 UTC

**Comment by yfrindel** [comment] 2016-12-01 20:37
Thank you, indeed I added the xslt file in my project and it work...but the xml generated is not enough filled as I would like...I need also the features descriptions in my report !

**Comment by rprouse** [comment] 2016-12-01 21:00
We don't provide transforms for producing reports. I have used [ReportUnit](http://relevantcodes.com/reportunit/) in the past to create HTML reports and like it. Check it out and see if it helps.

**Comment by yfrindel** [comment] 2016-12-02 08:42
Ok, thank you for your advice...
